services:
  backendv2:
    volumes:
      - ./backendv2:/app
      - /app/tmp  # Anonymous volume for Air's tmp directory
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "40000:40000"
    environment:
      - GO_ENV=development
    # Add healthcheck for better container management
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3 